### ISSUE TITLE
想询问一下 newApi 

### ISSUE THREAD

**Issue by yutiansut** [yinzishao/NewsScrapy#12]
## thepaper 爬虫爬出来的都是空的
![_20170119084050](https://cloud.githubusercontent.com/assets/11537812/22088984/05d6f99a-de23-11e6-917b-4b9bb9a50eef.png)

**Comment by yinzishao** [comment]
这是因为pipeline做了关键词处理https://github.com/yinzishao/NewsScrapy/blob/master/thepaper/thepaper/pipelines.py#L33
